epochs: 500
img_size : 224
latent_dim : 100
channels : 3
ds_path : 'C:/Users/ty/PycharmProjects/GAN/dataset'
batch_size: 8
shuffle: True
num_workers: 0
selective_test : False
#lr_dis: 5e-5
#lr_gen : 5e-5
lr_dis: 0.0002
lr_gen : 0.0002
image_resize: 224
val_samples : 16
ckpts_dir : "./ckpts_64"